server:
  port: ${MICRO_PORT:9998}

logging.pattern.console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(---){faint} %clr([%15.15t]){yellow} %clr(:){red} %clr(%m){faint}%n"

spring:
  application:
    name: gateway-service
  redis:
    host: localhost
    port: 6379
  output.ansi.enabled: ALWAYS
  cloud:
    gateway:
      routes:
        - id: challenge-service
          uri: http://127.0.0.1:8085
          predicates:
            - Path=/challenge-service/**
          filters:
            - RewritePath=/challenge-service/(?<path>.*), /$\{path}

        - id: admin-service
          uri: http://127.0.0.1:8082
          predicates:
            - Path=/admin-service/**
          filters:
            - RewritePath=/admin-service/(?<path>.*), /$\{path}

        - id: cohort-service
          uri: http://127.0.0.1:8087
          predicates:
            - Path=/cohort-service/**
          filters:
            - RewritePath=/cohort-service/(?<path>.*), /$\{path}


        - id: game-service
          uri: http://127.0.0.1:8089
          predicates:
            - Path=/game-service/**
          filters:
            - RewritePath=/game-service/(?<path>.*), /$\{path}


        - id: giftcode-service
          uri: http://127.0.0.1:8090
          predicates:
            - Path=/giftcode-service/**
          filters:
            - RewritePath=/giftcode-service/(?<path>.*), /$\{path}


        - id: item-shop-service
          uri: http://127.0.0.1:8092
          predicates:
            - Path=/item-shop-service/**
          filters:
            - RewritePath=/item-shop-service/(?<path>.*), /$\{path}


        - id: leaderboard-service
          uri: http://127.0.0.1:8097
          predicates:
            - Path=/leaderboard-service/**
          filters:
            - RewritePath=/leaderboard-service/(?<path>.*), /$\{path}


        - id: match-service
          uri: http://127.0.0.1:8093
          predicates:
            - Path=/match-service/**
          filters:
            - RewritePath=/match-service/(?<path>.*), /$\{path}


        - id: notification-service
          uri: http://127.0.0.1:8094
          predicates:
            - Path=/notification-service/**
          filters:
            - RewritePath=/notification-service/(?<path>.*), /$\{path}


        - id: security-service
          uri: http://127.0.0.1:8096
          predicates:
            - Path=/security-service/**
          filters:
            - RewritePath=/security-service/(?<path>.*), /$\{path}


        - id: user-service
          uri: http://127.0.0.1:8098
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<path>.*), /$\{path}





#        - id: customer-service
#          uri: http://localhost:8092
#          predicates:
#            - Path=/customer/**
#          filters:
#            - RewritePath=/customer/(?<path>.*), /$\{path}
#        - id: order-service
#          uri: http://localhost:8090
#          predicates:
#            - Path=/order/**
#          filters:
#            - RewritePath=/order/(?<path>.*), /$\{path}
#        - id: product-service
#          uri: http://localhost:8093
#          predicates:
#            - Path=/product/**
#          filters:
#            - RewritePath=/product/(?<path>.*), /$\{path}

#logging.level.io.github.resilience4j: DEBUG
#logging.level.org.springframework.cloud.gateway.filter.factory: TRACE